version: '3'

volumes:
    db-base:

services: 
    db:
        image: postgres:13.3
        restart: always
        volumes:
            - 'db-base:/var/lib/postgresql/data'
        env_file:
            - .env
        ports:
            - "5432:5432"
        